export const enemyDevlings = [
  {
    name: "Norbion",
    stats: {
      frontend: 1,
      backend: 4,
      "dev ego": 2,
      commits: 2,
      debugging: 3,
      Resilience: 5,
    },
    sprite: "../assets/heads/zom.png",
    nameSound: "../assets/sounds/norbion.mp3",
  },
  {
    name: "flyor",
    stats: {
      frontend: 1,
      backend: 5,
      "dev ego": 3,
      commits: 3,
      debugging: 4,
      Resilience: 2,
    },
    sprite: "../assets/heads/flyor.png",
    nameSound: "../assets/sounds/norbion.mp3",
  },
  {
    name: "Becca",
    frontend: 5,
    backend: 1,
    "dev ego": 4,
    commits: 3,
    debugging: 0,
    Resilience: 3,
    sprite: "../assets/heads/becca.png",
    nameSound: "../assets/sounds/becca.mp3",
    isPlanted: false,
    isWatered: false,
    isGrown: false,
  },
];
